dist: bionic
language: minimal
sudo: false
# Default `language: rust` has problems on nightly with rustfmt support

# only cache cargo subcommand binaries and .so libs
# the build artifacts take a lot of space and are slower to
# cache than to actually rebuild anyway...
# We need to cache the whole .cargo directory to keep the
# .crates.toml file.
cache:
  directories:
    - /home/travis/install
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf "$HOME"/.cargo/registry
before_script:
  - |
    export PATH="$HOME/.cargo/bin:$PATH"
    TRAVIS_RUST_VERSION="${TRAVIS_RUST_VERSION:-nightly}"
    if [ "$TRAVIS_RUST_VERSION" = 'nightly' ]; then
       printf -v RUSTFMT_VERSION '%s%s' '-' "$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)"
       printf -v CLIPPY_VERSION '%s%s' '-' "$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)"
       SMALLEST_COMPAT_RUST="$([[ "$RUSTFMT_VERSION" < "$CLIPPY_VERSION" ]] && echo "$RUSTFMT_VERSION" || echo "$CLIPPY_VERSION")"

       if command -v rustup 2>/dev/null; then
           rustup default "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
       else
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
       fi
    fi
    if command -v cargo >/dev/null; then
      export PATH="$HOME/.cargo/bin:$PATH"
      export XDG_RUNTIME_DIR="$PWD"'/socket'
      mkdir "$XDG_RUNTIME_DIR"
      cargo fetch
      rustup component add rustfmt
    fi
    if [ -n "$CLIPPY" ]; then
      rustup component add clippy --toolchain "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
    elif [ -n "$BUILD_FMT" ]; then
      rustup component add rustfmt --toolchain "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
    fi
script:
  - |
    if [ -n "$BUILD_FMT" ]; then
      cargo fmt --all -- --check
      # rustfmt --check # With: `src/*.rs` xor `"$(find -name '*.rs' -not -path './target/*')"`
    elif [ -n "$CLIPPY" ]; then
      cargo clippy --all -- -D warnings
    elif [ -n "$CARGO_TEST" ]; then
      cargo test --all --features "$FEATURES"
    fi

matrix:
  include:
    - rust: stable
      env: BUILD_FMT=1
    - rust: stable
      env: CLIPPY=1
    - rust: stable
      env: CARGO_TEST=1
    - stage: notify-website
      env:
        secure: 'WnECbOozwENwYI+KCv8xdLE1cb6w1xlSxD/3is6kKmj2+XhoKgkJodv4wzA8RyEZ14UKLh54IYKUsABKnonYwULn3OUCZu4e3qTZ3MvQooMlD+KpYyHy2BeyjET6V8hR+7dTLdhZLETsw6KuAf2aVkX5BiWkrWyW5fweQJLKcxaD+nlcmZZ20ll3mx4+dvhdsWUKmUohsAHc2n1eZyxaE3JJkyuIwLCBv9xk0097aUF1QFvaMexuKilMRM+4MwGTsqI6auraW7WWGVMoMz98T5vUkyEnHz9moyQy5Di8OIBfQp8Zjj2B8o+MHpgQZSMxHL4THpAMHhJy1QKD7Z4ZFPQqmUyoFH4lvohQIe3SAlxRY04a+qvxR6UT7n5fU9Z2WOci6vUyHTOVS781lPo7BnDA06//Vpy/f93205QfZI+kPyq4fqT3UL2v5o9qykud/cEU/jkGzgi9i61QVYXqArmElnwhQpZLdyHzFAloek/EUybFPxEX7jnsAzJyHCz1i8KiZvuTTHKnrw07ZPRMMM01Wae9yNevWkpzq2JAhWIE+qO1dIOo8sN/SvKOlunTudTJvQ9iN+5GYKs6p1F3nv6q+1HrEUHN6tw9UCgHK64HsvqnxdDwEd1ZE68veruHoTHN0mq8eVBXG29vGGiZTAgwkhBjSVZ3hzm5MSEj4JU='
      script:
        - email_author="$(git log -1 --pretty=format:'%an <%ce>')"
        - author="${email_author% *}"; git config --global user.name "$author"
        - email="${email_author#*<}"; email="${email::-1}"; git config --global user.email "$email"
        - git clone https://SamuelMarks:$GH_TOKEN@github.com/Fantom-foundation/fantom-dev-web
          && cd fantom-dev-web
        - echo "  | [$TRAVIS_REPO_SLUG](https://github.com/$TRAVIS_REPO_SLUG) | [$TRAVIS_COMMIT_MESSAGE](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT) |" >> CHANGESLOG.md
        - git add CHANGESLOG.md
        - git commit -m "[CHANGESLOG.md] $TRAVIS_REPO_SLUG - $TRAVIS_COMMIT_MESSAGE" 
        - git push -u origin master
